export default {
  "debit" : [
    "Tuition fees",
    "Textbooks",
    "Supplies",
    "Notebooks",
    "Stationery",
    "Rent",
    "Groceries",
    "Utilities",
    "Electricity bill",
    "Water bill",
    "Internet bill",
    "Phone bill",
    "Transportation",
    "Bus pass",
    "Uber or taxi",
    "Car maintenance",
    "Gas",
    "Meal plan",
    "Eating out",
    "Cafeteria",
    "Restaurant",
    "Takeout",
    "Coffee shops",
    "Software subscriptions",
    "Study materials",
    "Online courses",
    "Clothing",
    "Winter clothes",
    "Formal wear",
    "Casual wear",
    "Entertainment",
    "Movies",
    "Concerts",
    "Streaming services",
    "Video games",
    "Social activities",
    "Clubs",
    "Parties",
    "Events",
    "Gym membership",
    "Fitness classes",
    "Sports fees",
    "Team memberships",
    "Equipment",
    "Health insurance",
    "Doctor visits",
    "Prescription medication",
    "Dental visits",
    "Eye care",
    "Personal care",
    "Laundry",
    "Haircuts",
    "Skincare",
    "Toiletries",
    "Student organization fees",
    "Club memberships",
    "Event tickets",
    "Printing",
    "Photocopying",
    "Study abroad",
    "Travel expenses",
    "Accommodation",
    "Insurance",
    "Streaming services",
    "Music subscriptions",
    "Cloud storage",
    "App purchases"
  ],
  "credit": [
    "Part-time job",
    "Wages",
    "Tips",
    "Scholarships",
    "Merit-based scholarships",
    "Need-based scholarships",
    "Athletic scholarships",
    "Grants",
    "Federal grants",
    "State grants",
    "Private grants",
    "Student loans",
    "Federal loans",
    "Private loans",
    "Allowance from family",
    "Monthly allowance",
    "Special occasion money",
    "Internship stipend",
    "Paid internships",
    "Unpaid internships (expenses covered)",
    "Tutoring income",
    "Private tutoring",
    "Group tutoring",
    "Research assistant pay",
    "Campus work-study",
    "Library assistant",
    "Lab assistant",
    "Administrative jobs",
    "School refunds",
    "Overpaid tuition refunds",
    "Housing deposit refunds",
    "Selling textbooks",
    "Used textbook sales",
    "Freelance work",
    "Graphic design",
    "Writing",
    "Programming",
    "Tax refunds",
    "Federal tax refund",
    "State tax refund",
    "Gifts",
    "Birthday gifts",
    "Holiday gifts",
    "Special occasions",
    "Interest from savings",
    "Online surveys",
    "Market research participation",
    "Gig work",
    "Food delivery",
    "Ridesharing",
    "Freelance gigs",
    "Rental income",
    "Subletting",
    "Roommate rent share",
    "Cash prizes",
    "Competitions",
    "Contests",
    "Crowdfunding",
    "Project funding",
    "Charity funding",
    "Referral bonuses",
    "App referrals",
    "Service referrals",
    "Bank bonuses"
  ]
}
